### ISSUE TITLE
Add to Cart Displays on homepage

### ISSUE THREAD

**Issue by NafeesKhabir** [Darshanmodi1427/Darsh_Callforprice#2]
After activating still its showing add to cart in home page where its showing call for price on product description page.

**Comment by shankar2004nag** [comment]
Same issue at my end. Unable to view Call for price on the product description page.

**Comment by Darshanmodi1427** [comment]
@NafeesKhabir, For home page if you are using custom list.phtml file then you need to add code fir call for price section.

@shankar2004nag, Now check with latest module download I have tested with Magento 2.3.2 and default luma theme it's working fine. But make sure you have make enable module from admin configuration.

Thanks.
