### ISSUE TITLE
Admin Config (Email Templates) - Ignored

### ISSUE THREAD

**Issue by Tw0bit** [Darshanmodi1427/Darsh_Callforprice#4]
It seems that the module has been hard-coded to use the provided templates and not the area setup in the admin configuration:
- ->setTemplateIdentifier() in Controller/Adminhtml/Callforprice/Save.php and Controller/Form/Submit.php

It seems it should rather be setup like section 5 of this link https://webkul.com/blog/magento-2-send-transactional-email-programmatically-in-your-custom-module/
>> const XML_PATH_EMAIL_TEMPLATE_FIELD  = 'section/group/your_email_template_field_id';
    /* Here section and group refer to name of section and group where you create this field in configuration*/
 
>> $this->getTemplateId(self::XML_PATH_EMAIL_TEMPLATE_FIELD);

**Comment by Darshanmodi1427** [comment]
@Tw0bit  thanks for update. I will correct it in my next release.
