### ISSUE TITLE
Form is repeating two times 

### ISSUE THREAD

**Issue by Johnmathew12** [Darshanmodi1427/Darsh_Callforprice#5]
Dear Darsh , thank you for your great plugin . But now we are facing an issue . We are not able to submit call for price button for some product . After we filling the name , email etc and click the submit button then nothing is happen for some products . But for some other products it is working . We check the configuration of two products but it's are same . So we check the page source and found that <form name="cp_form" id="cp_form"> is coming two times in effected products . Please check

**Comment by Johnmathew12** [comment]
Dear Darsh , we found why this issue is coming . If our product hae option for call for price , then we add other product with call for price as a related product then the form is coming two times . if there is no related product then there will be no problem

**Comment by Johnmathew12** [comment]
this issue is occur in the product archive page , category page . If more than one product is coming in any page with call for price then call for price will not work

**Comment by Darshanmodi1427** [comment]
Hello John,

I have checked your issue. That is because of two time call-for-price from display on product page. So, for that you need to change form ID as per listing page form.

I have checked in in magento 2.3.1 and Luma theme current updated module is working fine.

Thanks for your response.
